/**
 * Full git workflow integration: status, diff, commit, branch, log, review.
 */

const BashTool = require('./BashTool');
const llm = require('../utils/llmClient');
const logger = require('../utils/logger');
const costTracker = require('../utils/costTracker');

class GitTool {
    /**
     * Check if a directory is inside a git repository
     */
    async isGitRepo(cwd = process.cwd()) {
        const result = await BashTool.execute('git rev-parse --is-inside-work-tree', { cwd, approved: true });
        return result.exitCode === 0;
    }

    /**
     * Get full git status
     */
    async status(cwd = process.cwd()) {
        const isRepo = await this.isGitRepo(cwd);
        if (!isRepo) return { branch: '(not a git repo)', ahead: 0, behind: 0, staged: [], unstaged: [], untracked: [], recentCommits: [], error: 'Not a git repository' };

        const [statusResult, branchResult] = await Promise.all([
            BashTool.execute('git status --porcelain=v2 --branch', { cwd, approved: true }),
            BashTool.execute('git log --oneline -5', { cwd, approved: true }),
        ]);

        return this._parseStatus(statusResult.stdout || '', branchResult.stdout || '');
    }

    _parseStatus(statusOutput, logOutput) {
        const lines = statusOutput.split('\n').filter(Boolean);
        const result = { branch: '', ahead: 0, behind: 0, staged: [], unstaged: [], untracked: [], recentCommits: [] };

        for (const line of lines) {
            if (line.startsWith('# branch.oid')) continue;
            if (line.startsWith('# branch.head')) result.branch = line.split(' ')[2];
            if (line.startsWith('# branch.ab')) {
                const m = line.match(/\+(\d+)\s+-(\d+)/);
                if (m) { result.ahead = parseInt(m[1]); result.behind = parseInt(m[2]); }
            }
            if (line.startsWith('1 ') || line.startsWith('2 ')) {
                const xy = line.slice(2, 4);
                const file = line.split('\t').pop();
                if (xy[0] !== '.' && xy[0] !== '?') result.staged.push({ status: xy[0], file });
                if (xy[1] !== '.' && xy[1] !== '?') result.unstaged.push({ status: xy[1], file });
            }
            if (line.startsWith('? ')) result.untracked.push(line.slice(2));
        }

        result.recentCommits = logOutput.split('\n').filter(Boolean).slice(0, 5);
        return result;
    }

    /**
     * Get diff (staged, unstaged, or specific file)
     */
    async diff(options = {}) {
        const { cwd = process.cwd(), staged = false, file, stat = false } = options;
        const isRepo = await this.isGitRepo(cwd);
        if (!isRepo) return { diff: '', hasChanges: false, staged, error: 'Not a git repository' };

        const flags = [
            staged ? '--staged' : '',
            stat ? '--stat' : '',
            '--no-color',
            file ? `-- ${JSON.stringify(file)}` : '',
        ].filter(Boolean).join(' ');

        const result = await BashTool.execute(`git diff ${flags}`, { cwd, approved: true });
        return {
            diff: result.stdout || '',
            hasChanges: (result.stdout || '').trim().length > 0,
            staged,
        };
    }

    /**
     * Stage files and create a commit with AI-generated message
     */
    async commit(options = {}) {
        const { cwd = process.cwd(), files = ['.'], message, autoMessage = false } = options;
        const isRepo = await this.isGitRepo(cwd);
        if (!isRepo) return { success: false, message: 'Not a git repository' };

        // Stage files
        const stageCmd = `git add ${files.map(f => JSON.stringify(f)).join(' ')}`;
        const stageResult = await BashTool.execute(stageCmd, { cwd, approved: true });
        if (stageResult.exitCode !== 0) return { success: false, message: stageResult.stderr || 'git add failed' };

        // Get staged diff for context
        const diffResult = await this.diff({ cwd, staged: true });
        if (!diffResult.hasChanges) return { success: false, message: 'Nothing staged to commit' };

        let commitMessage = message;
        if (!commitMessage || autoMessage) {
            commitMessage = await this._generateCommitMessage(diffResult.diff);
        }

        const result = await BashTool.execute(`git commit -m ${JSON.stringify(commitMessage)}`, { cwd, approved: true });
        if (result.exitCode !== 0) return { success: false, message: result.stderr || 'commit failed' };

        return {
            success: true,
            message: commitMessage,
            output: result.stdout,
            autoGenerated: !message || autoMessage,
        };
    }

    async _generateCommitMessage(diff) {
        if (!diff || diff.trim().length === 0) return 'chore: update files';
        const truncatedDiff = diff.slice(0, 4000);
        try {
            const response = await llm.chat({
                model: llm.model('fast'),
                max_tokens: 150,
                messages: [{
                    role: 'user',
                    content: `Generate a concise git commit message in conventional commits format (type: description) for this diff. Reply ONLY with the commit message, no explanation.\n\nDiff:\n${truncatedDiff}`,
                }],
            });
            costTracker.record({
                model: llm.model('fast'),
                inputTokens: response.usage.input_tokens,
                outputTokens: response.usage.output_tokens,
                queryType: 'git-commit',
            });
            return response.content[0].text.trim().replace(/^["']|["']$/g, '');
        } catch {
            return 'chore: update files';
        }
    }

    /**
     * AI-powered code review of staged changes or a file
     */
    async review(options = {}) {
        const { cwd = process.cwd(), staged = false, file, focus = '' } = options;
        const diffResult = await this.diff({ cwd, staged, file });
        if (!diffResult.hasChanges) return { review: 'No changes to review.', hasIssues: false };

        const diff = diffResult.diff.slice(0, 6000);
        const focusInstruction = focus
            ? `Focus especially on: ${focus}`
            : 'Focus on: bugs, security issues, performance problems, code style, and maintainability.';

        try {
            const response = await llm.chat({
                model: llm.model('smart'),
                max_tokens: 1500,
                system: `You are a senior software engineer conducting a code review. Be direct and specific.
Format your review as:
## Summary
(1-2 sentences)

## Issues Found
(list any bugs, security problems, or critical issues — be specific with line references)

## Suggestions
(improvements, not blockers)

## Verdict
LGTM | Needs Changes | Blocking Issues`,
                messages: [{ role: 'user', content: `Review this diff:\n${focusInstruction}\n\n\`\`\`diff\n${diff}\n\`\`\`` }],
            });
            costTracker.record({ model: llm.model('smart'), inputTokens: response.usage.input_tokens, outputTokens: response.usage.output_tokens, queryType: 'git-review' });
            const reviewText = response.content[0].text;
            return { review: reviewText, hasIssues: /blocking issues|needs changes/i.test(reviewText), diff: diffResult.diff };
        } catch (e) {
            return { review: `Review failed: ${e.message}`, hasIssues: false };
        }
    }

    /**
     * Get commit log
     */
    async log(options = {}) {
        const { cwd = process.cwd(), limit = 10, file, oneline = false } = options;
        const isRepo = await this.isGitRepo(cwd);
        if (!isRepo) return oneline ? [] : [];

        const format = oneline ? '--oneline' : '--pretty=format:"%H|%an|%ae|%ad|%s" --date=short';
        const fileFlag = file ? `-- ${JSON.stringify(file)}` : '';
        const result = await BashTool.execute(`git log -${limit} ${format} ${fileFlag}`, { cwd, approved: true });
        if (result.exitCode !== 0) return [];
        if (oneline) return result.stdout.split('\n').filter(Boolean);
        return result.stdout.split('\n').filter(Boolean).map(line => {
            const [hash, author, email, date, ...subjectParts] = line.replace(/^"|"$/g, '').split('|');
            return { hash: hash?.slice(0, 8), author, email, date, subject: subjectParts.join('|') };
        });
    }

    /**
     * List branches
     */
    async branches(cwd = process.cwd()) {
        const isRepo = await this.isGitRepo(cwd);
        if (!isRepo) return [];
        const result = await BashTool.execute('git branch -a --sort=-committerdate', { cwd, approved: true });
        if (result.exitCode !== 0) return [];
        return result.stdout.split('\n').filter(Boolean).map(b => ({
            name: b.replace(/^\*?\s+/, '').trim(),
            current: b.startsWith('*'),
        }));
    }
}

module.exports = new GitTool();
